// 특성의 기계적 효과 설명 (수치 명시) — 챔피언스 로스터 등장 특성 전체
export const ABILITY_FX: Record<string, string> = {
  'Adaptability': '자속 보정이 1.5배 → 2배가 된다',
  'Aerilate': '노말 기술이 비행 타입이 되고 위력 1.2배',
  'Aftermath': '접촉기로 쓰러지면 공격한 상대에게 최대 HP의 1/4 데미지',
  'Analytic': '그 턴의 마지막에 행동하면 기술 위력 1.3배',
  'Anger Point': '급소에 맞으면 공격이 +6랭크가 된다',
  'Anticipation': '등장 시 상대가 위험한 기술(약점·일격기)을 가졌는지 감지',
  'Armor Tail': '상대의 우선도 +1 이상 기술(선공기)을 무효화',
  'Aroma Veil': '자신과 아군에게 앵콜·도발 등 멘탈 계열 기술 무효',
  'Battle Armor': '급소에 맞지 않는다',
  'Battle Bond': '상대를 쓰러뜨리면 공격·특공·스핏 +1랭크',
  'Berserk': '공격으로 HP가 절반 이하가 되면 특공 +1랭크',
  'Big Pecks': '방어 랭크 하락 무효',
  'Blaze': 'HP 1/3 이하일 때 불꽃 기술 위력 1.5배',
  'Bulletproof': '구슬·폭탄 계열 기술 무효 (기합구슬, 진흙폭탄 등)',
  'Cheek Pouch': '나무열매를 먹으면 추가로 최대 HP의 1/3 회복',
  'Chlorophyll': '쾌청일 때 스핏 2배',
  'Clear Body': '상대에 의한 능력치 하락 무효',
  'Cloud Nine': '날씨의 효과가 모두 사라진다',
  'Competitive': '능력치가 하락당하면 특공 +2랭크',
  'Compound Eyes': '명중률 1.3배',
  'Contrary': '능력치 변화가 반대로 적용된다 (하락→상승)',
  'Corrosion': '강철·독 타입도 독 상태로 만들 수 있다',
  'Cud Chew': '나무열매를 먹으면 다음 턴 종료 시 한 번 더 먹는다',
  'Curious Medicine': '등장 시 아군의 능력치 변화를 초기화',
  'Cursed Body': '공격받으면 30% 확률로 그 기술을 사슬묶기 상태로',
  'Cute Charm': '접촉기에 맞으면 30% 확률로 상대를 헤롱헤롱',
  'Damp': '자폭·대폭발·유폭을 봉인',
  'Defiant': '능력치가 하락당하면 공격 +2랭크',
  'Disguise': '처음 받는 공격 1회 무효 (대신 최대 HP의 1/8 감소)',
  'Dragonize': '노말 기술이 드래곤 타입이 되고 위력 1.2배 (챔피언스 신특성)',
  'Drizzle': '등장 시 5턴간 비가 내린다',
  'Drought': '등장 시 5턴간 쾌청이 된다',
  'Dry Skin': '물 무효+HP 1/4 회복 · 비에서 매 턴 1/8 회복 · 쾌청에서 1/8 감소 · 불꽃 데미지 1.25배',
  'Early Bird': '잠듦 턴이 절반이 된다',
  'Earth Eater': '땅 기술 무효 + 최대 HP의 1/4 회복',
  'Eelevate': '땅 기술 무효 · 상대를 쓰러뜨리면 가장 높은 능력치 +1랭크 (챔피언스 신특성)',
  'Effect Spore': '접촉당하면 30% 확률로 독/마비/잠듦 중 하나',
  'Electric Surge': '등장 시 5턴간 일렉트릭필드 (전기 기술 1.3배)',
  'Electromorphosis': '공격받으면 충전 상태 (다음 전기 기술 2배)',
  'Fairy Aura': '모든 포켓몬의 페어리 기술 위력 1.33배',
  'Filter': '약점 공격의 데미지 0.75배',
  'Fire Mane': '불꽃 기술을 쓸 때 공격 실능 1.5배 (챔피언스 신특성)',
  'Flame Body': '접촉당하면 30% 확률로 화상',
  'Flash Fire': '불꽃 기술 무효 + 자신의 불꽃 기술 위력 1.5배',
  'Flower Veil': '풀 타입 아군의 능력치 하락·상태이상 방지',
  'Fluffy': '접촉기 데미지 0.5배 · 불꽃 데미지 2배',
  'Forecast': '날씨에 따라 타입이 변한다 (포워시)',
  'Forewarn': '등장 시 상대의 기술 하나를 확인',
  'Friend Guard': '아군이 받는 데미지 0.75배',
  'Frisk': '등장 시 상대의 지닌 도구를 확인',
  'Fur Coat': '물리 기술 데미지 0.5배',
  'Gale Wings': 'HP가 가득일 때 비행 기술 우선도 +1',
  'Gluttony': 'HP 절반 이하에서 나무열매를 일찍 먹는다',
  'Good as Gold': '변화 기술을 받지 않는다',
  'Gooey': '접촉한 상대의 스핏 -1랭크',
  'Guts': '상태이상일 때 공격 1.5배 (화상의 공격 절반 무시)',
  'Harvest': '턴 종료 시 50%(쾌청 100%) 확률로 사용한 나무열매 재생',
  'Healer': '턴 종료 시 50% 확률로 아군의 상태이상 치유 (챔피언스 조정)',
  'Heatproof': '불꽃 데미지 0.5배 · 화상 데미지 절반',
  'Heavy Metal': '몸무게 2배 (풀묶기 등에 영향)',
  'Hospitality': '등장 시 아군 HP를 최대 HP의 1/4 회복',
  'Huge Power': '공격 실능 2배',
  'Hunger Switch': '매 턴 배부른 모습↔배고픈 모습 전환 (모르페코)',
  'Hustle': '공격 1.5배 · 물리 기술 명중률 0.8배',
  'Hydration': '비일 때 턴 종료 시 상태이상 회복',
  'Hyper Cutter': '공격 랭크 하락 무효',
  'Ice Body': '눈일 때 매 턴 최대 HP의 1/16 회복',
  'Illuminate': '명중률 하락 무효 · 상대 회피율 상승 무시',
  'Illusion': '파티 마지막 포켓몬의 모습으로 등장',
  'Immunity': '독 상태가 되지 않는다',
  'Imposter': '등장 시 맞은편 상대로 변신',
  'Infiltrator': '대타출동·리플렉터·빛의장막을 무시하고 공격',
  'Innards Out': '쓰러질 때 남아있던 HP만큼 상대에게 데미지',
  'Inner Focus': '풀죽지 않는다 · 위협 무효',
  'Insomnia': '잠들지 않는다',
  'Intimidate': '등장 시 상대의 공격 -1랭크',
  'Iron Fist': '펀치 기술 위력 1.2배',
  'Justified': '악 기술에 맞으면 공격 +1랭크',
  'Keen Eye': '명중률 하락 무효 · 상대 회피율 상승 무시',
  'Klutz': '지닌 도구의 효과가 사라진다',
  'Leaf Guard': '쾌청일 때 상태이상에 걸리지 않는다',
  'Levitate': '땅 기술 무효',
  'Light Metal': '몸무게 0.5배',
  'Lightning Rod': '전기 기술 무효 + 특공 +1랭크',
  'Limber': '마비되지 않는다',
  'Liquid Voice': '소리 기술이 물 타입이 된다',
  'Long Reach': '자신의 기술이 접촉 판정을 받지 않는다',
  'Magic Bounce': '변화 기술을 상대에게 되돌려보낸다',
  'Magic Guard': '공격 이외의 데미지(독·모래·스텔스록 등)를 받지 않는다',
  'Magician': '기술을 맞힌 상대의 도구를 빼앗는다',
  'Magma Armor': '얼음 상태가 되지 않는다',
  'Marvel Scale': '상태이상일 때 방어 1.5배',
  'Mega Launcher': '파동 기술 위력 1.5배 (파동탄, 용의파동 등)',
  'Mega Sol': '자신의 기술이 항상 쾌청 상태인 것처럼 적용된다 (챔피언스 신특성)',
  'Merciless': '독 상태인 상대에게 반드시 급소',
  'Mimicry': '필드에 따라 자신의 타입이 변한다',
  'Minus': '아군에 플러스/마이너스가 있으면 특공 1.5배',
  'Mirror Armor': '받은 능력치 하락을 상대에게 반사',
  'Mold Breaker': '상대의 특성(부유·멀티스케일 등)을 무시하고 공격',
  'Moody': '매 턴 한 능력 +2랭크, 다른 능력 -1랭크',
  'Motor Drive': '전기 기술 무효 + 스핏 +1랭크',
  'Moxie': '상대를 쓰러뜨리면 공격 +1랭크',
  'Multiscale': 'HP가 가득일 때 받는 데미지 0.5배',
  'Mummy': '접촉한 상대의 특성을 미라로 바꾼다',
  'Natural Cure': '교대하면 상태이상이 회복된다',
  'No Guard': '서로의 기술이 반드시 명중한다',
  'Oblivious': '헤롱헤롱·도발 무효 · 위협 무효',
  'Opportunist': '상대의 능력치 상승을 자신도 따라한다',
  'Overcoat': '가루 기술(포자 등)과 날씨 데미지 무효',
  'Overgrow': 'HP 1/3 이하일 때 풀 기술 위력 1.5배',
  'Own Tempo': '혼란되지 않는다 · 위협 무효',
  'Parental Bond': '1번의 공격이 2회 연속 (2타는 위력 25%)',
  'Pickpocket': '접촉당했을 때 상대의 도구를 훔친다',
  'Pickup': '아군이 소모한 도구를 주울 수 있다',
  'Piercing Drill': '접촉기가 방어(프로텍트류)를 관통해 1/4 데미지를 준다 (챔피언스 신특성)',
  'Pixilate': '노말 기술이 페어리 타입이 되고 위력 1.2배',
  'Plus': '아군에 플러스/마이너스가 있으면 특공 1.5배',
  'Poison Heal': '독 데미지 대신 매 턴 최대 HP의 1/8 회복',
  'Poison Point': '접촉당하면 30% 확률로 독',
  'Poison Touch': '자신의 접촉기에 30% 독 부가',
  'Prankster': '변화 기술 우선도 +1 (악 타입에게는 무효)',
  'Pressure': '상대가 기술 PP를 2씩 소모',
  'Protean': '기술을 쓰기 직전 그 기술의 타입으로 변한다 → 모든 공격이 자속 1.5배',
  'Libero': '기술을 쓰기 직전 그 기술의 타입으로 변한다 → 모든 공격이 자속 1.5배',
  'Pure Power': '공격 실능 2배',
  'Purifying Salt': '상태이상 무효 · 고스트 데미지 0.5배',
  'Queenly Majesty': '상대의 우선도 +1 이상 기술(선공기)을 무효화',
  'Quick Draw': '30% 확률로 우선 행동',
  'Quick Feet': '상태이상일 때 스핏 1.5배 (마비 감속 무시)',
  'Rain Dish': '비일 때 매 턴 최대 HP의 1/16 회복',
  'Receiver': '쓰러진 아군의 특성을 이어받는다',
  'Reckless': '반동 기술 위력 1.2배',
  'Refrigerate': '노말 기술이 얼음 타입이 되고 위력 1.2배',
  'Regenerator': '교대해서 들어가면 최대 HP의 1/3 회복',
  'Ripen': '나무열매의 효과 2배',
  'Rivalry': '같은 성별 상대에게 1.25배, 다른 성별에게 0.75배',
  'Rock Head': '반동 데미지를 받지 않는다',
  'Rough Skin': '접촉한 상대에게 최대 HP의 1/8 데미지',
  'Sand Force': '모래바람에서 바위·땅·강철 기술 위력 1.3배',
  'Sand Rush': '모래바람에서 스핏 2배',
  'Sand Spit': '공격받으면 모래바람을 일으킨다',
  'Sand Stream': '등장 시 5턴간 모래바람',
  'Sand Veil': '모래바람에서 회피율 1.25배',
  'Sap Sipper': '풀 기술 무효 + 공격 +1랭크',
  'Scrappy': '노말·격투 기술이 고스트에게 적중 · 위협 무효',
  'Screen Cleaner': '등장 시 양쪽의 리플렉터·빛의장막 제거',
  'Shadow Tag': '상대가 교대할 수 없다',
  'Sharpness': '베기 기술 위력 1.5배 (성스러운칼, 리프블레이드 등)',
  'Shed Skin': '매 턴 33% 확률로 상태이상 회복',
  'Sheer Force': '부가효과가 있는 기술 위력 1.3배 (부가효과는 사라짐)',
  'Shell Armor': '급소에 맞지 않는다',
  'Shield Dust': '상대 기술의 부가효과(풀죽음·랭크하락 등)를 받지 않는다',
  'Skill Link': '연속기가 항상 최대 횟수로 나간다',
  'Slush Rush': '눈일 때 스핏 2배',
  'Sniper': '급소 데미지가 1.5배 → 2.25배',
  'Snow Cloak': '눈일 때 회피율 1.25배',
  'Snow Warning': '등장 시 5턴간 눈',
  'Solar Power': '쾌청일 때 특공 1.5배, 매 턴 최대 HP의 1/8 감소',
  'Solid Rock': '약점 공격의 데미지 0.75배',
  'Soundproof': '소리 기술 무효 (폭음파, 하이퍼보이스 등)',
  'Speed Boost': '매 턴 종료 시 스핏 +1랭크',
  'Spicy Spray': '공격받으면 공격한 상대를 화상 상태로 만든다 (챔피언스 신특성)',
  'Stall': '항상 그 우선도에서 마지막에 행동',
  'Stalwart': '상대의 유인 효과를 무시하고 지정한 대상 공격',
  'Stamina': '공격받으면 방어 +1랭크',
  'Stance Change': '공격 기술 사용 시 블레이드폼, 킹실드 사용 시 실드폼 (킬가르도)',
  'Static': '접촉당하면 30% 확률로 마비',
  'Steadfast': '풀죽을 때마다 스핏 +1랭크',
  'Stench': '공격 시 10% 확률로 상대를 풀죽게 한다',
  'Sticky Hold': '지닌 도구를 빼앗기지 않는다',
  'Strong Jaw': '무는 기술 위력 1.5배 (깨물어부수기 등)',
  'Sturdy': 'HP 가득일 때 일격에 쓰러지지 않고 HP 1 남김 · 일격기 무효',
  'Suction Cups': '강제 교대(드래곤테일 등) 무효',
  'Super Luck': '급소율 +1단계',
  'Supersweet Syrup': '첫 등장 시 상대의 회피율 -1랭크',
  'Supreme Overlord': '쓰러진 아군 1마리당 공격·특공 10% 상승 (최대 30%)',
  'Surge Surfer': '일렉트릭필드에서 스핏 2배',
  'Swarm': 'HP 1/3 이하일 때 벌레 기술 위력 1.5배',
  'Sweet Veil': '자신과 아군이 잠들지 않는다',
  'Swift Swim': '비일 때 스핏 2배',
  'Symbiosis': '아군이 도구를 소모하면 자신의 도구를 넘겨준다',
  'Synchronize': '받은 독·마비·화상을 상대에게도 옮긴다',
  'Tangled Feet': '혼란일 때 회피율 2배',
  'Technician': '위력 60 이하 기술의 위력 1.5배',
  'Telepathy': '아군의 공격을 받지 않는다',
  'Thick Fat': '불꽃·얼음 기술 데미지 0.5배',
  'Torrent': 'HP 1/3 이하일 때 물 기술 위력 1.5배',
  'Tough Claws': '접촉기 위력 1.3배',
  'Toxic Debris': '물리 공격을 받으면 상대 필드에 독압정 설치',
  'Trace': '등장 시 상대의 특성을 복사',
  'Unaware': '상대의 능력치 랭크 변화를 무시하고 계산',
  'Unburden': '지닌 도구가 소모되면 스핏 2배',
  'Unnerve': '상대가 나무열매를 먹지 못한다',
  'Unseen Fist': '접촉기가 방어(프로텍트류)를 관통한다 (연격 우라오스)',
  'Vital Spirit': '잠들지 않는다',
  'Volt Absorb': '전기 기술 무효 + 최대 HP의 1/4 회복',
  'Wandering Spirit': '접촉한 상대와 특성을 교환',
  'Water Absorb': '물 기술 무효 + 최대 HP의 1/4 회복',
  'Water Bubble': '물 기술 위력 2배 · 불꽃 데미지 0.5배 · 화상 무효',
  'Weak Armor': '물리 기술에 맞으면 방어 -1, 스핏 +2랭크',
  'White Smoke': '상대에 의한 능력치 하락 무효',
  'Zero to Hero': '교대했다가 다시 나오면 마이티폼이 된다 (돌핀맨)',
  'Storm Drain': '물 기술 무효 + 특공 +1랭크',
  'Well-Baked Body': '불꽃 기술 무효 + 방어 +2랭크',
  'Wind Rider': '바람 기술 무효 + 공격 +1랭크',
};
