// 도구의 기계적 효과 설명 (수치 명시) — 챔피언스 합법 도구 전체 (메가스톤은 엔진에서 자동 생성)
export const ITEM_FX: Record<string, string> = {
  // 구애/보조 배틀 도구
  choicescarf: '스핏 1.5배. 대신 처음 선택한 기술만 계속 쓸 수 있다 (교대하면 해제)',
  expertbelt: '약점을 찌른 기술의 위력 1.2배',
  focussash: 'HP가 가득일 때 일격에 쓰러질 데미지를 받으면 HP 1로 버틴다 (1회용)',
  focusband: '쓰러질 데미지를 받아도 10% 확률로 HP 1로 버틴다',
  leftovers: '매 턴 종료 시 최대 HP의 1/16 회복',
  lifeorb: '공격 기술의 위력 1.3배. 대신 공격할 때마다 최대 HP의 1/10 감소',
  muscleband: '물리 기술의 위력 1.1배',
  wiseglasses: '특수 기술의 위력 1.1배',
  mentalherb: '헤롱헤롱·앵콜·도발·사슬묶기·회복봉인에 걸리면 즉시 해제 (1회용)',
  whiteherb: '능력치가 하락하면 즉시 원래대로 되돌린다 (1회용)',
  kingsrock: '데미지를 주는 기술에 10% 풀죽음 효과 추가',
  quickclaw: '20% 확률로 같은 우선도에서 먼저 행동',
  scopelens: '급소율 +1단계 (기본 1/24 → 1/8)',
  brightpowder: '상대 기술의 명중률 0.9배',
  widelens: '자신의 기술 명중률 1.1배',
  zoomlens: '상대보다 늦게 행동하는 턴에 명중률 1.2배',
  metronome: '같은 기술을 연속 사용하면 위력 증가 (1회당 +20%, 최대 2배)',
  shellbell: '준 데미지의 1/8만큼 HP 회복',
  shedshell: '그림자밟기 등 교대를 막는 효과를 무시하고 교대 가능',
  ironball: '스핏 0.5배. 부유·비행 타입도 땅 기술에 맞게 된다',
  bigroot: 'HP 흡수 기술·씨뿌리기의 회복량 1.3배',
  lightclay: '리플렉터·빛의장막 지속이 5턴 → 8턴',
  damprock: '자신이 내린 비 지속이 5턴 → 8턴',
  heatrock: '자신이 만든 쾌청 지속이 5턴 → 8턴',
  icyrock: '자신이 내린 눈 지속이 5턴 → 8턴',
  smoothrock: '자신이 일으킨 모래바람 지속이 5턴 → 8턴',
  lightball: '피카츄 전용 — 공격·특공 실능 2배',
  // 타입 강화 (1.2배)
  blackbelt: '격투 기술의 위력 1.2배',
  blackglasses: '악 기술의 위력 1.2배',
  charcoal: '불꽃 기술의 위력 1.2배',
  dragonfang: '드래곤 기술의 위력 1.2배',
  fairyfeather: '페어리 기술의 위력 1.2배',
  hardstone: '바위 기술의 위력 1.2배',
  magnet: '전기 기술의 위력 1.2배',
  metalcoat: '강철 기술의 위력 1.2배',
  miracleseed: '풀 기술의 위력 1.2배',
  mysticwater: '물 기술의 위력 1.2배',
  nevermeltice: '얼음 기술의 위력 1.2배',
  poisonbarb: '독 기술의 위력 1.2배',
  sharpbeak: '비행 기술의 위력 1.2배',
  silkscarf: '노말 기술의 위력 1.2배',
  silverpowder: '벌레 기술의 위력 1.2배',
  softsand: '땅 기술의 위력 1.2배',
  spelltag: '고스트 기술의 위력 1.2배',
  twistedspoon: '에스퍼 기술의 위력 1.2배',
  // 회복·상태이상 열매
  sitrusberry: 'HP가 1/2 이하가 되면 최대 HP의 1/4 회복 (1회용)',
  oranberry: 'HP가 1/2 이하가 되면 HP 10 회복 (1회용)',
  lumberry: '상태이상·혼란에 걸리면 즉시 회복 (1회용)',
  chestoberry: '잠들면 즉시 깨어난다 (1회용)',
  cheriberry: '마비되면 즉시 회복 (1회용)',
  pechaberry: '독에 걸리면 즉시 회복 (1회용)',
  rawstberry: '화상을 입으면 즉시 회복 (1회용)',
  aspearberry: '얼음 상태가 되면 즉시 회복 (1회용)',
  persimberry: '혼란되면 즉시 회복 (1회용)',
  leppaberry: 'PP가 0이 된 기술의 PP를 10 회복 (1회용)',
  // 반감 열매 (약점으로 맞을 때 데미지 0.5배, 1회용)
  babiriberry: '약점인 강철 기술의 데미지 0.5배 (1회용)',
  chartiberry: '약점인 바위 기술의 데미지 0.5배 (1회용)',
  chilanberry: '노말 기술의 데미지 0.5배 (약점 아니어도 발동, 1회용)',
  chopleberry: '약점인 격투 기술의 데미지 0.5배 (1회용)',
  cobaberry: '약점인 비행 기술의 데미지 0.5배 (1회용)',
  colburberry: '약점인 악 기술의 데미지 0.5배 (1회용)',
  habanberry: '약점인 드래곤 기술의 데미지 0.5배 (1회용)',
  kasibberry: '약점인 고스트 기술의 데미지 0.5배 (1회용)',
  kebiaberry: '약점인 독 기술의 데미지 0.5배 (1회용)',
  occaberry: '약점인 불꽃 기술의 데미지 0.5배 (1회용)',
  passhoberry: '약점인 물 기술의 데미지 0.5배 (1회용)',
  payapaberry: '약점인 에스퍼 기술의 데미지 0.5배 (1회용)',
  rindoberry: '약점인 풀 기술의 데미지 0.5배 (1회용)',
  roseliberry: '약점인 페어리 기술의 데미지 0.5배 (1회용)',
  shucaberry: '약점인 땅 기술의 데미지 0.5배 (1회용)',
  tangaberry: '약점인 벌레 기술의 데미지 0.5배 (1회용)',
  wacanberry: '약점인 전기 기술의 데미지 0.5배 (1회용)',
  yacheberry: '약점인 얼음 기술의 데미지 0.5배 (1회용)',
};
